/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/animation/index.vue')['default']
    Echarts: typeof import('./src/components/echarts/index.vue')['default']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    Header: typeof import('./src/components/header/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    IconBox: typeof import('./src/components/Layout/IconBox/index.vue')['default']
    LayerTree: typeof import('./src/components/layerTree/index.vue')['default']
    LeaseTitle: typeof import('./src/components/leaseTitle/index.vue')['default']
    LeftBox: typeof import('./src/components/Layout/leftBox/index.vue')['default']
    Player: typeof import('./src/components/player/index.vue')['default']
    RightBox: typeof import('./src/components/Layout/rightBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterNav: typeof import('./src/components/routerNav/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    Weather: typeof import('./src/components/weather/index.vue')['default']
  }
}
