/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/animation/index.vue')['default']
    Box: typeof import('./src/components/Box/index.vue')['default']
    CityPlan: typeof import('./src/components/FloatButton/cityPlan.vue')['default']
    copy: typeof import('./src/components/leftBox copy/index.vue')['default']
    Echarts: typeof import('./src/components/echarts/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FloatButton: typeof import('./src/components/FloatButton/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    IconBox: typeof import('./src/components/Layout/IconBox/index.vue')['default']
    LayerTree: typeof import('./src/components/layerTree/index.vue')['default']
    Lease_title: typeof import('./src/components/Lease_title/index.vue')['default']
    LeaseTitle: typeof import('./src/components/leaseTitle/index.vue')['default']
    Left_box: typeof import('./src/components/left_box.vue')['default']
    LeftBox: typeof import('./src/components/Layout/leftBox/index.vue')['default']
    LeftToolBox: typeof import('./src/components/LeftToolBox/index.vue')['default']
    Player: typeof import('./src/components/player/index.vue')['default']
    Right_box: typeof import('./src/components/right_box.vue')['default']
    RightBox: typeof import('./src/components/Layout/rightBox/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterNav: typeof import('./src/components/routerNav/index.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    SubTitle: typeof import('./src/components/SubTitle/SubTitle.vue')['default']
    SubTitleReverse: typeof import('./src/components/SubTitle/SubTitleReverse.vue')['default']
    V3Echarts: typeof import('./src/components/V3Echarts/index.vue')['default']
    Weather: typeof import('./src/components/weather/index.vue')['default']
  }
}
